'use client';

import { ArrowDownUp, ChevronDown, Moon, RefreshCw, Sun, TrendingUp } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Currency = { code: string; name: string; symbol: string };
const currencies: Currency[] = [
  { code: 'RUB', name: 'Российский рубль', symbol: '₽' }, { code: 'USD', name: 'Доллар США', symbol: '$' }, { code: 'EUR', name: 'Евро', symbol: '€' }, { code: 'CNY', name: 'Китайский юань', symbol: '¥' }, { code: 'GBP', name: 'Фунт стерлингов', symbol: '£' }, { code: 'KZT', name: 'Казахстанский тенге', symbol: '₸' }, { code: 'TRY', name: 'Турецкая лира', symbol: '₺' }, { code: 'AED', name: 'Дирхам ОАЭ', symbol: 'د.إ' },
];
const fallbackRates: Record<string, number> = { USD: 1, RUB: 86.409515, EUR: 0.861401, CNY: 6.736206, GBP: 0.738359, KZT: 461.733033, TRY: 48.275416, AED: 3.6725 };
const getCurrency = (code: string) => currencies.find((item) => item.code === code)!;

export default function Home() {
  const [amount, setAmount] = useState('10 000'); const [from, setFrom] = useState('RUB'); const [to, setTo] = useState('USD');
  const [rates, setRates] = useState(fallbackRates); const [updatedAt, setUpdatedAt] = useState(''); const [loading, setLoading] = useState(false); const [dark, setDark] = useState(false); const [history, setHistory] = useState<Record<string, { date: string; value: number }[]>>({});
  const rate = rates[to] / rates[from]; const numericAmount = Number(amount.replace(/\s/g, '').replace(',', '.')) || 0; const result = numericAmount * rate;
  const formattedResult = useMemo(() => new Intl.NumberFormat('ru-RU', { maximumFractionDigits: result < 1 ? 4 : 2 }).format(result), [result]);
  async function loadRate() { setLoading(true); try { const response = await fetch('https://open.er-api.com/v6/latest/USD'); if (!response.ok) throw new Error(); const data = await response.json() as { time_last_update_utc: string; rates: Record<string, number> }; setRates(data.rates); setUpdatedAt(new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(data.time_last_update_utc))); } catch { setUpdatedAt('показан расчётный курс'); } finally { setLoading(false); } }
  async function loadHistory() { const dates = Array.from({ length: 31 }, (_, i) => { const day = new Date(); day.setDate(day.getDate() - i); return day; }); const records = await Promise.all(dates.map(async (day) => { const stamp = day.toISOString().slice(0, 10).replaceAll('-', '/'); try { const response = await fetch(`https://www.cbr-xml-daily.ru/archive/${stamp}/daily_json.js`, { signal: AbortSignal.timeout(8000) }); if (!response.ok) return null; const data = await response.json() as { Valute: Record<string, { Value: number; Nominal: number }> }; return { date: new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: '2-digit' }).format(day), values: Object.fromEntries(['USD', 'EUR', 'CNY', 'KZT'].map((code) => [code, data.Valute[code].Value / data.Valute[code].Nominal])) }; } catch { return null; } })); const points = records.filter((item): item is NonNullable<typeof item> => item !== null).reverse().slice(-22); if (points.length) setHistory({ 'USD/RUB': points.map((p) => ({ date: p.date, value: p.values.USD })), 'EUR/RUB': points.map((p) => ({ date: p.date, value: p.values.EUR })), 'CNY/RUB': points.map((p) => ({ date: p.date, value: p.values.CNY })), 'RUB/KZT': points.map((p) => ({ date: p.date, value: 1 / p.values.KZT })) }); }
  useEffect(() => { void loadRate(); void loadHistory(); const refresh = window.setInterval(() => { void loadRate(); void loadHistory(); }, 60 * 60 * 1000); return () => window.clearInterval(refresh); }, []);
  const rateText = (a: string, b: string) => (rates[b] / rates[a]).toLocaleString('ru-RU', { maximumFractionDigits: 2 });
  return <div className={dark ? 'theme-dark' : ''}><main className="min-h-screen bg-[#f3f7fa] text-[#122238]"><div className="mx-auto max-w-6xl px-5 py-6 sm:px-8 sm:py-10">
    <header className="mb-12 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#1259c3] text-xl font-black text-white shadow-lg shadow-blue-200">₿</div><span className="text-xl font-bold tracking-tight">Курсометр</span></div><div className="flex items-center gap-3"><button onClick={() => setDark(!dark)} className="theme-toggle grid size-10 place-items-center rounded-full bg-white text-slate-500 shadow-sm transition hover:text-[#1259c3]" aria-label={dark ? 'Включить светлую тему' : 'Включить тёмную тему'}>{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</button><span className="hidden rounded-full bg-white px-4 py-2 text-xs font-semibold text-slate-500 shadow-sm sm:block">Валютный калькулятор</span></div></header>
    <section className="grid gap-8 lg:grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)] lg:items-center"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-[#2870d7]">Конвертация без лишнего</p><h1 className="max-w-xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl">Сколько стоит<br /><span className="text-[#1259c3]">ваша валюта?</span></h1><p className="mt-5 max-w-lg text-base leading-relaxed text-slate-600">Проверяйте курсы и переводите деньги в нужную валюту за пару секунд.</p><div className="mt-7 flex flex-wrap gap-3 text-sm text-slate-500"><span className="flex items-center gap-2 rounded-full bg-white px-4 py-2 shadow-sm"><span className="size-2 rounded-full bg-emerald-500" />Проверяем каждый час</span><span className="flex items-center gap-2 rounded-full bg-white px-4 py-2 shadow-sm"><TrendingUp className="size-4 text-[#1259c3]" />8 популярных валют</span></div></div>
    <section className="overflow-hidden rounded-[2rem] bg-white p-5 shadow-[0_24px_70px_rgba(31,70,120,.14)] sm:p-8" aria-label="Конвертер валют"><div className="mb-7 flex items-center justify-between"><h2 className="text-xl font-bold">Конвертер</h2><button onClick={() => void loadRate()} className="refresh-button rounded-full bg-slate-100 p-2.5 text-slate-500 transition hover:bg-blue-50 hover:text-[#1259c3]" aria-label="Обновить курс"><RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} /></button></div><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_40px_minmax(0,1fr)] sm:items-end"><div className="min-w-0"><label className="mb-2 block text-sm font-semibold text-slate-500" htmlFor="amount">Отдаёте</label><div className="flex min-w-0 rounded-2xl border border-slate-200 bg-slate-50 p-2 focus-within:border-[#1259c3]"><input id="amount" value={amount} inputMode="decimal" onChange={(e) => setAmount(e.target.value)} className="min-w-0 flex-1 bg-transparent px-2 text-xl font-bold outline-none sm:text-2xl" aria-label="Сумма для конвертации" /><CurrencySelect value={from} onChange={setFrom} /></div></div><button onClick={() => { setFrom(to); setTo(from); }} className="swap-button mx-auto grid size-10 place-items-center rounded-full border-4 border-white bg-[#1259c3] text-white shadow-md transition hover:rotate-180" aria-label="Поменять валюты местами"><ArrowDownUp className="size-4 rotate-90" /></button><div className="min-w-0"><label className="mb-2 block text-sm font-semibold text-slate-500" htmlFor="result">Получаете</label><div className="flex min-w-0 rounded-2xl bg-[#eaf3ff] p-2"><output id="result" className="min-w-0 flex-1 truncate px-2 py-2 text-xl font-bold text-[#1259c3] sm:text-2xl">{formattedResult}</output><CurrencySelect value={to} onChange={setTo} /></div></div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-5 text-xs text-slate-500"><span>1 {from} = {rate.toLocaleString('ru-RU', { maximumFractionDigits: 5 })} {to}</span><span>{updatedAt ? `курс на ${updatedAt}` : 'загрузка курса...'}</span></div></section></section>
    <section className="mt-16 border-t border-slate-200 pt-7"><div className="mb-5 flex flex-wrap items-end justify-between gap-2"><p className="text-sm font-bold uppercase tracking-[.15em] text-slate-400">Популярные пары</p><p className="text-xs text-slate-500">Конвертация: ExchangeRate-API · графики за месяц: ЦБ РФ · курс на {updatedAt || 'загрузку'}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['USD','RUB'],['EUR','RUB'],['CNY','RUB'],['RUB','KZT']].map(([a,b]) => <button key={`${a}-${b}`} onClick={() => { setFrom(a); setTo(b); }} className="popular-pair rounded-2xl bg-white px-5 py-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span><b>{a}</b><span className="mx-2 text-slate-300">/</span><b>{b}</b></span><span className="font-semibold text-[#1259c3]">{rateText(a, b)}</span></div><TrendLine points={history[`${a}/${b}`]} /></button>)}</div></section>
  </div></main></div>;
}
function CurrencySelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { const currency = getCurrency(value); return <div className="relative min-w-0"><select value={value} onChange={(e) => onChange(e.target.value)} className="currency-select w-[86px] appearance-none rounded-xl bg-white py-3 pl-2 pr-6 text-sm font-bold text-slate-700 outline-none sm:w-[96px]"><option value={value}>{currency.symbol} {currency.code}</option>{currencies.filter((item) => item.code !== value).map((item) => <option key={item.code} value={item.code}>{item.symbol} {item.code} — {item.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-1 top-1/2 size-4 -translate-y-1/2 text-slate-400" /></div>; }

function TrendLine({ points = [] }: { points?: { date: string; value: number }[] }) { if (points.length < 2) return <div className="mt-3 flex h-[62px] items-center justify-center rounded-lg bg-slate-50 text-[10px] text-slate-400">Загружаем историю за месяц…</div>; const values = points.map((item) => item.value); const min = Math.min(...values); const max = Math.max(...values); const span = max - min || max * 0.01; const coords = points.map((item, index) => `${24 + (index * 148) / (points.length - 1)},${44 - ((item.value - min) / span) * 34}`).join(' '); const rising = values.at(-1)! >= values[0]; const format = (value: number) => value.toLocaleString('ru-RU', { maximumFractionDigits: value < 10 ? 3 : 2 }); return <div className="mt-3"><svg className="h-[62px] w-full" viewBox="0 0 180 62" preserveAspectRatio="none" role="img" aria-label="График курса за последний месяц"><line x1="24" x2="172" y1="44" y2="44" stroke="#cbd5e1" strokeWidth="1" /><line x1="24" x2="24" y1="5" y2="44" stroke="#cbd5e1" strokeWidth="1" /><line x1="24" x2="172" y1="10" y2="10" stroke="#e2e8f0" strokeWidth="1" strokeDasharray="2 2" /><polyline points={coords} fill="none" stroke={rising ? '#10b981' : '#f59e0b'} strokeWidth="2" vectorEffect="non-scaling-stroke" /><text x="0" y="11" fontSize="8" fill="#64748b">{format(max)}</text><text x="0" y="45" fontSize="8" fill="#64748b">{format(min)}</text><text x="24" y="58" fontSize="8" fill="#64748b">{points[0].date}</text><text x="145" y="58" fontSize="8" fill="#64748b">{points.at(-1)!.date}</text></svg><div className="mt-1 flex justify-between text-[10px] text-slate-400"><span>значение курса</span><span>дата</span></div></div>; }
