'use client';

import { ArrowDownUp, ChevronDown, RefreshCw, TrendingUp } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Currency = { code: string; name: string; symbol: string };
const currencies: Currency[] = [
  { code: 'RUB', name: 'Российский рубль', symbol: '₽' }, { code: 'USD', name: 'Доллар США', symbol: '$' },
  { code: 'EUR', name: 'Евро', symbol: '€' }, { code: 'CNY', name: 'Китайский юань', symbol: '¥' },
  { code: 'GBP', name: 'Фунт стерлингов', symbol: '£' }, { code: 'KZT', name: 'Казахстанский тенге', symbol: '₸' },
  { code: 'TRY', name: 'Турецкая лира', symbol: '₺' }, { code: 'AED', name: 'Дирхам ОАЭ', symbol: 'د.إ' },
];
const getCurrency = (code: string) => currencies.find((item) => item.code === code)!;

export default function Home() {
  const [amount, setAmount] = useState('10 000'); const [from, setFrom] = useState('RUB'); const [to, setTo] = useState('USD');
  const [rate, setRate] = useState(0.0108); const [date, setDate] = useState(''); const [loading, setLoading] = useState(false);
  const numericAmount = Number(amount.replace(/\s/g, '').replace(',', '.')) || 0; const result = numericAmount * rate;
  const formattedResult = useMemo(() => new Intl.NumberFormat('ru-RU', { maximumFractionDigits: result < 1 ? 4 : 2 }).format(result), [result]);
  async function loadRate() { setLoading(true); try { const response = await fetch(`https://api.frankfurter.dev/v1/latest?base=${from}&symbols=${to}`); if (!response.ok) throw new Error(); const data = await response.json() as { date: string; rates: Record<string, number> }; setRate(data.rates[to]); setDate(data.date); } catch { setDate('расчётный курс'); } finally { setLoading(false); } }
  useEffect(() => { void loadRate(); }, [from, to]);
  return <main className="min-h-screen bg-[#f3f7fa] text-[#122238]"><div className="mx-auto max-w-6xl px-5 py-6 sm:px-8 sm:py-10">
    <header className="mb-12 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#1259c3] text-xl font-black text-white shadow-lg shadow-blue-200">₿</div><span className="text-xl font-bold tracking-tight">Курсометр</span></div><span className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-slate-500 shadow-sm">Валютный калькулятор</span></header>
    <section className="grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-center"><div><p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-[#2870d7]">Конвертация без лишнего</p><h1 className="max-w-xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl">Сколько стоит<br /><span className="text-[#1259c3]">ваша валюта?</span></h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-slate-600">Проверяйте курсы и переводите деньги в нужную валюту за пару секунд.</p><div className="mt-9 flex flex-wrap gap-3 text-sm text-slate-500"><span className="flex items-center gap-2 rounded-full bg-white px-4 py-2 shadow-sm"><span className="size-2 rounded-full bg-emerald-500" />Курсы обновляются автоматически</span><span className="flex items-center gap-2 rounded-full bg-white px-4 py-2 shadow-sm"><TrendingUp className="size-4 text-[#1259c3]" />8 популярных валют</span></div></div>
    <section className="rounded-[2rem] bg-white p-5 shadow-[0_24px_70px_rgba(31,70,120,.14)] sm:p-8" aria-label="Конвертер валют"><div className="mb-7 flex items-center justify-between"><h2 className="text-xl font-bold">Конвертер</h2><button onClick={() => void loadRate()} className="rounded-full bg-slate-100 p-2.5 text-slate-500 transition hover:bg-blue-50 hover:text-[#1259c3]" aria-label="Обновить курс"><RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} /></button></div><div className="space-y-3"><label className="block text-sm font-semibold text-slate-500" htmlFor="amount">Отдаёте</label><div className="flex rounded-2xl border border-slate-200 bg-slate-50 p-2 focus-within:border-[#1259c3]"><input id="amount" value={amount} inputMode="decimal" onChange={(e) => setAmount(e.target.value)} className="min-w-0 flex-1 bg-transparent px-3 text-2xl font-bold outline-none" aria-label="Сумма для конвертации" /><CurrencySelect value={from} onChange={setFrom} /></div><button onClick={() => { setFrom(to); setTo(from); }} className="relative z-10 mx-auto grid size-10 place-items-center rounded-full border-4 border-white bg-[#1259c3] text-white shadow-md transition hover:rotate-180" aria-label="Поменять валюты местами"><ArrowDownUp className="size-4" /></button><label className="block text-sm font-semibold text-slate-500" htmlFor="result">Получаете</label><div className="flex rounded-2xl bg-[#eaf3ff] p-2"><output id="result" className="min-w-0 flex-1 overflow-hidden px-3 py-2 text-2xl font-bold text-[#1259c3]">{formattedResult}</output><CurrencySelect value={to} onChange={setTo} /></div></div><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5 text-xs text-slate-500"><span>1 {from} = {rate.toLocaleString('ru-RU', { maximumFractionDigits: 5 })} {to}</span><span>{date ? `на ${date}` : 'загрузка курса...'}</span></div></section></section>
    <section className="mt-16 border-t border-slate-200 pt-7"><p className="mb-5 text-sm font-bold uppercase tracking-[.15em] text-slate-400">Популярные пары</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['USD','RUB','92,46'],['EUR','RUB','99,82'],['CNY','RUB','12,74'],['GBP','RUB','118,56']].map(([a,b,value]) => <button key={a} onClick={() => { setFrom(a); setTo(b); }} className="flex items-center justify-between rounded-2xl bg-white px-5 py-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span><b>{a}</b><span className="mx-2 text-slate-300">/</span><b>{b}</b></span><span className="font-semibold text-[#1259c3]">{value}</span></button>)}</div></section>
  </div></main>;
}
function CurrencySelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { const currency = getCurrency(value); return <div className="relative"><select value={value} onChange={(e) => onChange(e.target.value)} className="appearance-none rounded-xl bg-white py-3 pl-3 pr-8 text-sm font-bold text-slate-700 outline-none"><option value={value}>{currency.symbol} {currency.code}</option>{currencies.filter((item) => item.code !== value).map((item) => <option key={item.code} value={item.code}>{item.symbol} {item.code} — {item.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2 top-1/2 size-4 -translate-y-1/2 text-slate-400" /></div>; }
